language: python

python:
  - '3.6'

install:
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - pip install nose
  - pip install coverage

script:
  - nosetests --with-coverage --cover-package prwlr

notifications:
  email:
    - dariusz.izak@ibb.waw.pl
    - psiedlecki@gmail.com
    on_success: never
    on_failure: always
